/// Nomes de países por ISO-3166-1 alpha-2 (CLDR/umpirsky).
/// Fonte: código ISO; a UI nunca usa o nome cru do Places.
/// Gerado — mapa global, não chaves manuais para poucos países.

class IsoCountryNames {
  IsoCountryNames._();

  static const Map<String, Map<String, String>> byLanguage = {
    'en': {
      'ad': 'Andorra',
      'ae': 'United Arab Emirates',
      'af': 'Afghanistan',
      'ag': 'Antigua & Barbuda',
      'ai': 'Anguilla',
      'al': 'Albania',
      'am': 'Armenia',
      'ao': 'Angola',
      'aq': 'Antarctica',
      'ar': 'Argentina',
      'as': 'American Samoa',
      'at': 'Austria',
      'au': 'Australia',
      'aw': 'Aruba',
      'ax': 'Åland Islands',
      'az': 'Azerbaijan',
      'ba': 'Bosnia & Herzegovina',
      'bb': 'Barbados',
      'bd': 'Bangladesh',
      'be': 'Belgium',
      'bf': 'Burkina Faso',
      'bg': 'Bulgaria',
      'bh': 'Bahrain',
      'bi': 'Burundi',
      'bj': 'Benin',
      'bl': 'St. Barthélemy',
      'bm': 'Bermuda',
      'bn': 'Brunei',
      'bo': 'Bolivia',
      'bq': 'Caribbean Netherlands',
      'br': 'Brazil',
      'bs': 'Bahamas',
      'bt': 'Bhutan',
      'bv': 'Bouvet Island',
      'bw': 'Botswana',
      'by': 'Belarus',
      'bz': 'Belize',
      'ca': 'Canada',
      'cc': 'Cocos (Keeling) Islands',
      'cd': 'Congo - Kinshasa',
      'cf': 'Central African Republic',
      'cg': 'Congo - Brazzaville',
      'ch': 'Switzerland',
      'ci': 'Côte d’Ivoire',
      'ck': 'Cook Islands',
      'cl': 'Chile',
      'cm': 'Cameroon',
      'cn': 'China',
      'co': 'Colombia',
      'cr': 'Costa Rica',
      'cu': 'Cuba',
      'cv': 'Cape Verde',
      'cw': 'Curaçao',
      'cx': 'Christmas Island',
      'cy': 'Cyprus',
      'cz': 'Czechia',
      'de': 'Germany',
      'dj': 'Djibouti',
      'dk': 'Denmark',
      'dm': 'Dominica',
      'do': 'Dominican Republic',
      'dz': 'Algeria',
      'ec': 'Ecuador',
      'ee': 'Estonia',
      'eg': 'Egypt',
      'eh': 'Western Sahara',
      'er': 'Eritrea',
      'es': 'Spain',
      'et': 'Ethiopia',
      'fi': 'Finland',
      'fj': 'Fiji',
      'fk': 'Falkland Islands',
      'fm': 'Micronesia',
      'fo': 'Faroe Islands',
      'fr': 'France',
      'ga': 'Gabon',
      'gb': 'United Kingdom',
      'gd': 'Grenada',
      'ge': 'Georgia',
      'gf': 'French Guiana',
      'gg': 'Guernsey',
      'gh': 'Ghana',
      'gi': 'Gibraltar',
      'gl': 'Greenland',
      'gm': 'Gambia',
      'gn': 'Guinea',
      'gp': 'Guadeloupe',
      'gq': 'Equatorial Guinea',
      'gr': 'Greece',
      'gs': 'South Georgia & South Sandwich Islands',
      'gt': 'Guatemala',
      'gu': 'Guam',
      'gw': 'Guinea-Bissau',
      'gy': 'Guyana',
      'hk': 'Hong Kong SAR China',
      'hm': 'Heard & McDonald Islands',
      'hn': 'Honduras',
      'hr': 'Croatia',
      'ht': 'Haiti',
      'hu': 'Hungary',
      'id': 'Indonesia',
      'ie': 'Ireland',
      'il': 'Israel',
      'im': 'Isle of Man',
      'in': 'India',
      'io': 'British Indian Ocean Territory',
      'iq': 'Iraq',
      'ir': 'Iran',
      'is': 'Iceland',
      'it': 'Italy',
      'je': 'Jersey',
      'jm': 'Jamaica',
      'jo': 'Jordan',
      'jp': 'Japan',
      'ke': 'Kenya',
      'kg': 'Kyrgyzstan',
      'kh': 'Cambodia',
      'ki': 'Kiribati',
      'km': 'Comoros',
      'kn': 'St. Kitts & Nevis',
      'kp': 'North Korea',
      'kr': 'South Korea',
      'kw': 'Kuwait',
      'ky': 'Cayman Islands',
      'kz': 'Kazakhstan',
      'la': 'Laos',
      'lb': 'Lebanon',
      'lc': 'St. Lucia',
      'li': 'Liechtenstein',
      'lk': 'Sri Lanka',
      'lr': 'Liberia',
      'ls': 'Lesotho',
      'lt': 'Lithuania',
      'lu': 'Luxembourg',
      'lv': 'Latvia',
      'ly': 'Libya',
      'ma': 'Morocco',
      'mc': 'Monaco',
      'md': 'Moldova',
      'me': 'Montenegro',
      'mf': 'St. Martin',
      'mg': 'Madagascar',
      'mh': 'Marshall Islands',
      'mk': 'North Macedonia',
      'ml': 'Mali',
      'mm': 'Myanmar (Burma)',
      'mn': 'Mongolia',
      'mo': 'Macao SAR China',
      'mp': 'Northern Mariana Islands',
      'mq': 'Martinique',
      'mr': 'Mauritania',
      'ms': 'Montserrat',
      'mt': 'Malta',
      'mu': 'Mauritius',
      'mv': 'Maldives',
      'mw': 'Malawi',
      'mx': 'Mexico',
      'my': 'Malaysia',
      'mz': 'Mozambique',
      'na': 'Namibia',
      'nc': 'New Caledonia',
      'ne': 'Niger',
      'nf': 'Norfolk Island',
      'ng': 'Nigeria',
      'ni': 'Nicaragua',
      'nl': 'Netherlands',
      'no': 'Norway',
      'np': 'Nepal',
      'nr': 'Nauru',
      'nu': 'Niue',
      'nz': 'New Zealand',
      'om': 'Oman',
      'pa': 'Panama',
      'pe': 'Peru',
      'pf': 'French Polynesia',
      'pg': 'Papua New Guinea',
      'ph': 'Philippines',
      'pk': 'Pakistan',
      'pl': 'Poland',
      'pm': 'St. Pierre & Miquelon',
      'pn': 'Pitcairn Islands',
      'pr': 'Puerto Rico',
      'ps': 'Palestinian Territories',
      'pt': 'Portugal',
      'pw': 'Palau',
      'py': 'Paraguay',
      'qa': 'Qatar',
      're': 'Réunion',
      'ro': 'Romania',
      'rs': 'Serbia',
      'ru': 'Russia',
      'rw': 'Rwanda',
      'sa': 'Saudi Arabia',
      'sb': 'Solomon Islands',
      'sc': 'Seychelles',
      'sd': 'Sudan',
      'se': 'Sweden',
      'sg': 'Singapore',
      'sh': 'St. Helena',
      'si': 'Slovenia',
      'sj': 'Svalbard & Jan Mayen',
      'sk': 'Slovakia',
      'sl': 'Sierra Leone',
      'sm': 'San Marino',
      'sn': 'Senegal',
      'so': 'Somalia',
      'sr': 'Suriname',
      'ss': 'South Sudan',
      'st': 'São Tomé & Príncipe',
      'sv': 'El Salvador',
      'sx': 'Sint Maarten',
      'sy': 'Syria',
      'sz': 'Eswatini',
      'tc': 'Turks & Caicos Islands',
      'td': 'Chad',
      'tf': 'French Southern Territories',
      'tg': 'Togo',
      'th': 'Thailand',
      'tj': 'Tajikistan',
      'tk': 'Tokelau',
      'tl': 'Timor-Leste',
      'tm': 'Turkmenistan',
      'tn': 'Tunisia',
      'to': 'Tonga',
      'tr': 'Turkey',
      'tt': 'Trinidad & Tobago',
      'tv': 'Tuvalu',
      'tw': 'Taiwan',
      'tz': 'Tanzania',
      'ua': 'Ukraine',
      'ug': 'Uganda',
      'um': 'U.S. Outlying Islands',
      'us': 'United States',
      'uy': 'Uruguay',
      'uz': 'Uzbekistan',
      'va': 'Vatican City',
      'vc': 'St. Vincent & Grenadines',
      've': 'Venezuela',
      'vg': 'British Virgin Islands',
      'vi': 'U.S. Virgin Islands',
      'vn': 'Vietnam',
      'vu': 'Vanuatu',
      'wf': 'Wallis & Futuna',
      'ws': 'Samoa',
      'ye': 'Yemen',
      'yt': 'Mayotte',
      'za': 'South Africa',
      'zm': 'Zambia',
      'zw': 'Zimbabwe',
    },
    'pt': {
      'ad': 'Andorra',
      'ae': 'Emirados Árabes Unidos',
      'af': 'Afeganistão',
      'ag': 'Antígua e Barbuda',
      'ai': 'Anguila',
      'al': 'Albânia',
      'am': 'Armênia',
      'ao': 'Angola',
      'aq': 'Antártida',
      'ar': 'Argentina',
      'as': 'Samoa Americana',
      'at': 'Áustria',
      'au': 'Austrália',
      'aw': 'Aruba',
      'ax': 'Ilhas Aland',
      'az': 'Azerbaijão',
      'ba': 'Bósnia e Herzegovina',
      'bb': 'Barbados',
      'bd': 'Bangladesh',
      'be': 'Bélgica',
      'bf': 'Burquina Faso',
      'bg': 'Bulgária',
      'bh': 'Bahrein',
      'bi': 'Burundi',
      'bj': 'Benin',
      'bl': 'São Bartolomeu',
      'bm': 'Bermudas',
      'bn': 'Brunei',
      'bo': 'Bolívia',
      'bq': 'Países Baixos Caribenhos',
      'br': 'Brasil',
      'bs': 'Bahamas',
      'bt': 'Butão',
      'bv': 'Ilha Bouvet',
      'bw': 'Botsuana',
      'by': 'Bielorrússia',
      'bz': 'Belize',
      'ca': 'Canadá',
      'cc': 'Ilhas Cocos (Keeling)',
      'cd': 'Congo - Kinshasa',
      'cf': 'República Centro-Africana',
      'cg': 'República do Congo',
      'ch': 'Suíça',
      'ci': 'Costa do Marfim',
      'ck': 'Ilhas Cook',
      'cl': 'Chile',
      'cm': 'Camarões',
      'cn': 'China',
      'co': 'Colômbia',
      'cr': 'Costa Rica',
      'cu': 'Cuba',
      'cv': 'Cabo Verde',
      'cw': 'Curaçao',
      'cx': 'Ilha Christmas',
      'cy': 'Chipre',
      'cz': 'Tchéquia',
      'de': 'Alemanha',
      'dj': 'Djibuti',
      'dk': 'Dinamarca',
      'dm': 'Dominica',
      'do': 'República Dominicana',
      'dz': 'Argélia',
      'ec': 'Equador',
      'ee': 'Estônia',
      'eg': 'Egito',
      'eh': 'Saara Ocidental',
      'er': 'Eritreia',
      'es': 'Espanha',
      'et': 'Etiópia',
      'fi': 'Finlândia',
      'fj': 'Fiji',
      'fk': 'Ilhas Malvinas',
      'fm': 'Micronésia',
      'fo': 'Ilhas Faroe',
      'fr': 'França',
      'ga': 'Gabão',
      'gb': 'Reino Unido',
      'gd': 'Granada',
      'ge': 'Geórgia',
      'gf': 'Guiana Francesa',
      'gg': 'Guernsey',
      'gh': 'Gana',
      'gi': 'Gibraltar',
      'gl': 'Groenlândia',
      'gm': 'Gâmbia',
      'gn': 'Guiné',
      'gp': 'Guadalupe',
      'gq': 'Guiné Equatorial',
      'gr': 'Grécia',
      'gs': 'Ilhas Geórgia do Sul e Sandwich do Sul',
      'gt': 'Guatemala',
      'gu': 'Guam',
      'gw': 'Guiné-Bissau',
      'gy': 'Guiana',
      'hk': 'Hong Kong, RAE da China',
      'hm': 'Ilhas Heard e McDonald',
      'hn': 'Honduras',
      'hr': 'Croácia',
      'ht': 'Haiti',
      'hu': 'Hungria',
      'id': 'Indonésia',
      'ie': 'Irlanda',
      'il': 'Israel',
      'im': 'Ilha de Man',
      'in': 'Índia',
      'io': 'Território Britânico do Oceano Índico',
      'iq': 'Iraque',
      'ir': 'Irã',
      'is': 'Islândia',
      'it': 'Itália',
      'je': 'Jersey',
      'jm': 'Jamaica',
      'jo': 'Jordânia',
      'jp': 'Japão',
      'ke': 'Quênia',
      'kg': 'Quirguistão',
      'kh': 'Camboja',
      'ki': 'Quiribati',
      'km': 'Comores',
      'kn': 'São Cristóvão e Névis',
      'kp': 'Coreia do Norte',
      'kr': 'Coreia do Sul',
      'kw': 'Kuwait',
      'ky': 'Ilhas Cayman',
      'kz': 'Cazaquistão',
      'la': 'Laos',
      'lb': 'Líbano',
      'lc': 'Santa Lúcia',
      'li': 'Liechtenstein',
      'lk': 'Sri Lanka',
      'lr': 'Libéria',
      'ls': 'Lesoto',
      'lt': 'Lituânia',
      'lu': 'Luxemburgo',
      'lv': 'Letônia',
      'ly': 'Líbia',
      'ma': 'Marrocos',
      'mc': 'Mônaco',
      'md': 'Moldova',
      'me': 'Montenegro',
      'mf': 'São Martinho',
      'mg': 'Madagascar',
      'mh': 'Ilhas Marshall',
      'mk': 'Macedônia do Norte',
      'ml': 'Mali',
      'mm': 'Mianmar (Birmânia)',
      'mn': 'Mongólia',
      'mo': 'Macau, RAE da China',
      'mp': 'Ilhas Marianas do Norte',
      'mq': 'Martinica',
      'mr': 'Mauritânia',
      'ms': 'Montserrat',
      'mt': 'Malta',
      'mu': 'Maurício',
      'mv': 'Maldivas',
      'mw': 'Malaui',
      'mx': 'México',
      'my': 'Malásia',
      'mz': 'Moçambique',
      'na': 'Namíbia',
      'nc': 'Nova Caledônia',
      'ne': 'Níger',
      'nf': 'Ilha Norfolk',
      'ng': 'Nigéria',
      'ni': 'Nicarágua',
      'nl': 'Países Baixos',
      'no': 'Noruega',
      'np': 'Nepal',
      'nr': 'Nauru',
      'nu': 'Niue',
      'nz': 'Nova Zelândia',
      'om': 'Omã',
      'pa': 'Panamá',
      'pe': 'Peru',
      'pf': 'Polinésia Francesa',
      'pg': 'Papua-Nova Guiné',
      'ph': 'Filipinas',
      'pk': 'Paquistão',
      'pl': 'Polônia',
      'pm': 'São Pedro e Miquelão',
      'pn': 'Ilhas Pitcairn',
      'pr': 'Porto Rico',
      'ps': 'Territórios palestinos',
      'pt': 'Portugal',
      'pw': 'Palau',
      'py': 'Paraguai',
      'qa': 'Catar',
      're': 'Reunião',
      'ro': 'Romênia',
      'rs': 'Sérvia',
      'ru': 'Rússia',
      'rw': 'Ruanda',
      'sa': 'Arábia Saudita',
      'sb': 'Ilhas Salomão',
      'sc': 'Seicheles',
      'sd': 'Sudão',
      'se': 'Suécia',
      'sg': 'Singapura',
      'sh': 'Santa Helena',
      'si': 'Eslovênia',
      'sj': 'Svalbard e Jan Mayen',
      'sk': 'Eslováquia',
      'sl': 'Serra Leoa',
      'sm': 'San Marino',
      'sn': 'Senegal',
      'so': 'Somália',
      'sr': 'Suriname',
      'ss': 'Sudão do Sul',
      'st': 'São Tomé e Príncipe',
      'sv': 'El Salvador',
      'sx': 'Sint Maarten',
      'sy': 'Síria',
      'sz': 'Essuatíni',
      'tc': 'Ilhas Turcas e Caicos',
      'td': 'Chade',
      'tf': 'Territórios Franceses do Sul',
      'tg': 'Togo',
      'th': 'Tailândia',
      'tj': 'Tadjiquistão',
      'tk': 'Tokelau',
      'tl': 'Timor-Leste',
      'tm': 'Turcomenistão',
      'tn': 'Tunísia',
      'to': 'Tonga',
      'tr': 'Turquia',
      'tt': 'Trinidad e Tobago',
      'tv': 'Tuvalu',
      'tw': 'Taiwan',
      'tz': 'Tanzânia',
      'ua': 'Ucrânia',
      'ug': 'Uganda',
      'um': 'Ilhas Menores Distantes dos EUA',
      'us': 'Estados Unidos',
      'uy': 'Uruguai',
      'uz': 'Uzbequistão',
      'va': 'Cidade do Vaticano',
      'vc': 'São Vicente e Granadinas',
      've': 'Venezuela',
      'vg': 'Ilhas Virgens Britânicas',
      'vi': 'Ilhas Virgens Americanas',
      'vn': 'Vietnã',
      'vu': 'Vanuatu',
      'wf': 'Wallis e Futuna',
      'ws': 'Samoa',
      'ye': 'Iêmen',
      'yt': 'Mayotte',
      'za': 'África do Sul',
      'zm': 'Zâmbia',
      'zw': 'Zimbábue',
    },
    'es': {
      'ad': 'Andorra',
      'ae': 'Emiratos Árabes Unidos',
      'af': 'Afganistán',
      'ag': 'Antigua y Barbuda',
      'ai': 'Anguila',
      'al': 'Albania',
      'am': 'Armenia',
      'ao': 'Angola',
      'aq': 'Antártida',
      'ar': 'Argentina',
      'as': 'Samoa Americana',
      'at': 'Austria',
      'au': 'Australia',
      'aw': 'Aruba',
      'ax': 'Islas Åland',
      'az': 'Azerbaiyán',
      'ba': 'Bosnia y Herzegovina',
      'bb': 'Barbados',
      'bd': 'Bangladés',
      'be': 'Bélgica',
      'bf': 'Burkina Faso',
      'bg': 'Bulgaria',
      'bh': 'Baréin',
      'bi': 'Burundi',
      'bj': 'Benín',
      'bl': 'San Bartolomé',
      'bm': 'Bermudas',
      'bn': 'Brunéi',
      'bo': 'Bolivia',
      'bq': 'Caribe neerlandés',
      'br': 'Brasil',
      'bs': 'Bahamas',
      'bt': 'Bután',
      'bv': 'Isla Bouvet',
      'bw': 'Botsuana',
      'by': 'Bielorrusia',
      'bz': 'Belice',
      'ca': 'Canadá',
      'cc': 'Islas Cocos',
      'cd': 'República Democrática del Congo',
      'cf': 'República Centroafricana',
      'cg': 'Congo',
      'ch': 'Suiza',
      'ci': 'Côte d’Ivoire',
      'ck': 'Islas Cook',
      'cl': 'Chile',
      'cm': 'Camerún',
      'cn': 'China',
      'co': 'Colombia',
      'cr': 'Costa Rica',
      'cu': 'Cuba',
      'cv': 'Cabo Verde',
      'cw': 'Curazao',
      'cx': 'Isla de Navidad',
      'cy': 'Chipre',
      'cz': 'Chequia',
      'de': 'Alemania',
      'dj': 'Yibuti',
      'dk': 'Dinamarca',
      'dm': 'Dominica',
      'do': 'República Dominicana',
      'dz': 'Argelia',
      'ec': 'Ecuador',
      'ee': 'Estonia',
      'eg': 'Egipto',
      'eh': 'Sáhara Occidental',
      'er': 'Eritrea',
      'es': 'España',
      'et': 'Etiopía',
      'fi': 'Finlandia',
      'fj': 'Fiyi',
      'fk': 'Islas Malvinas',
      'fm': 'Micronesia',
      'fo': 'Islas Feroe',
      'fr': 'Francia',
      'ga': 'Gabón',
      'gb': 'Reino Unido',
      'gd': 'Granada',
      'ge': 'Georgia',
      'gf': 'Guayana Francesa',
      'gg': 'Guernsey',
      'gh': 'Ghana',
      'gi': 'Gibraltar',
      'gl': 'Groenlandia',
      'gm': 'Gambia',
      'gn': 'Guinea',
      'gp': 'Guadalupe',
      'gq': 'Guinea Ecuatorial',
      'gr': 'Grecia',
      'gs': 'Islas Georgia del Sur y Sandwich del Sur',
      'gt': 'Guatemala',
      'gu': 'Guam',
      'gw': 'Guinea-Bisáu',
      'gy': 'Guyana',
      'hk': 'RAE de Hong Kong (China)',
      'hm': 'Islas Heard y McDonald',
      'hn': 'Honduras',
      'hr': 'Croacia',
      'ht': 'Haití',
      'hu': 'Hungría',
      'id': 'Indonesia',
      'ie': 'Irlanda',
      'il': 'Israel',
      'im': 'Isla de Man',
      'in': 'India',
      'io': 'Territorio Británico del Océano Índico',
      'iq': 'Irak',
      'ir': 'Irán',
      'is': 'Islandia',
      'it': 'Italia',
      'je': 'Jersey',
      'jm': 'Jamaica',
      'jo': 'Jordania',
      'jp': 'Japón',
      'ke': 'Kenia',
      'kg': 'Kirguistán',
      'kh': 'Camboya',
      'ki': 'Kiribati',
      'km': 'Comoras',
      'kn': 'San Cristóbal y Nieves',
      'kp': 'Corea del Norte',
      'kr': 'Corea del Sur',
      'kw': 'Kuwait',
      'ky': 'Islas Caimán',
      'kz': 'Kazajistán',
      'la': 'Laos',
      'lb': 'Líbano',
      'lc': 'Santa Lucía',
      'li': 'Liechtenstein',
      'lk': 'Sri Lanka',
      'lr': 'Liberia',
      'ls': 'Lesoto',
      'lt': 'Lituania',
      'lu': 'Luxemburgo',
      'lv': 'Letonia',
      'ly': 'Libia',
      'ma': 'Marruecos',
      'mc': 'Mónaco',
      'md': 'Moldavia',
      'me': 'Montenegro',
      'mf': 'San Martín',
      'mg': 'Madagascar',
      'mh': 'Islas Marshall',
      'mk': 'Macedonia del Norte',
      'ml': 'Mali',
      'mm': 'Myanmar (Birmania)',
      'mn': 'Mongolia',
      'mo': 'RAE de Macao (China)',
      'mp': 'Islas Marianas del Norte',
      'mq': 'Martinica',
      'mr': 'Mauritania',
      'ms': 'Montserrat',
      'mt': 'Malta',
      'mu': 'Mauricio',
      'mv': 'Maldivas',
      'mw': 'Malaui',
      'mx': 'México',
      'my': 'Malasia',
      'mz': 'Mozambique',
      'na': 'Namibia',
      'nc': 'Nueva Caledonia',
      'ne': 'Níger',
      'nf': 'Isla Norfolk',
      'ng': 'Nigeria',
      'ni': 'Nicaragua',
      'nl': 'Países Bajos',
      'no': 'Noruega',
      'np': 'Nepal',
      'nr': 'Nauru',
      'nu': 'Niue',
      'nz': 'Nueva Zelanda',
      'om': 'Omán',
      'pa': 'Panamá',
      'pe': 'Perú',
      'pf': 'Polinesia Francesa',
      'pg': 'Papúa Nueva Guinea',
      'ph': 'Filipinas',
      'pk': 'Pakistán',
      'pl': 'Polonia',
      'pm': 'San Pedro y Miquelón',
      'pn': 'Islas Pitcairn',
      'pr': 'Puerto Rico',
      'ps': 'Territorios Palestinos',
      'pt': 'Portugal',
      'pw': 'Palaos',
      'py': 'Paraguay',
      'qa': 'Catar',
      're': 'Reunión',
      'ro': 'Rumanía',
      'rs': 'Serbia',
      'ru': 'Rusia',
      'rw': 'Ruanda',
      'sa': 'Arabia Saudí',
      'sb': 'Islas Salomón',
      'sc': 'Seychelles',
      'sd': 'Sudán',
      'se': 'Suecia',
      'sg': 'Singapur',
      'sh': 'Santa Elena',
      'si': 'Eslovenia',
      'sj': 'Svalbard y Jan Mayen',
      'sk': 'Eslovaquia',
      'sl': 'Sierra Leona',
      'sm': 'San Marino',
      'sn': 'Senegal',
      'so': 'Somalia',
      'sr': 'Surinam',
      'ss': 'Sudán del Sur',
      'st': 'Santo Tomé y Príncipe',
      'sv': 'El Salvador',
      'sx': 'Sint Maarten',
      'sy': 'Siria',
      'sz': 'Esuatini',
      'tc': 'Islas Turcas y Caicos',
      'td': 'Chad',
      'tf': 'Territorios Australes Franceses',
      'tg': 'Togo',
      'th': 'Tailandia',
      'tj': 'Tayikistán',
      'tk': 'Tokelau',
      'tl': 'Timor-Leste',
      'tm': 'Turkmenistán',
      'tn': 'Túnez',
      'to': 'Tonga',
      'tr': 'Turquía',
      'tt': 'Trinidad y Tobago',
      'tv': 'Tuvalu',
      'tw': 'Taiwán',
      'tz': 'Tanzania',
      'ua': 'Ucrania',
      'ug': 'Uganda',
      'um': 'Islas menores alejadas de EE. UU.',
      'us': 'Estados Unidos',
      'uy': 'Uruguay',
      'uz': 'Uzbekistán',
      'va': 'Ciudad del Vaticano',
      'vc': 'San Vicente y las Granadinas',
      've': 'Venezuela',
      'vg': 'Islas Vírgenes Británicas',
      'vi': 'Islas Vírgenes de EE. UU.',
      'vn': 'Vietnam',
      'vu': 'Vanuatu',
      'wf': 'Wallis y Futuna',
      'ws': 'Samoa',
      'ye': 'Yemen',
      'yt': 'Mayotte',
      'za': 'Sudáfrica',
      'zm': 'Zambia',
      'zw': 'Zimbabue',
    },
    'fr': {
      'ad': 'Andorre',
      'ae': 'Émirats arabes unis',
      'af': 'Afghanistan',
      'ag': 'Antigua-et-Barbuda',
      'ai': 'Anguilla',
      'al': 'Albanie',
      'am': 'Arménie',
      'ao': 'Angola',
      'aq': 'Antarctique',
      'ar': 'Argentine',
      'as': 'Samoa américaines',
      'at': 'Autriche',
      'au': 'Australie',
      'aw': 'Aruba',
      'ax': 'Îles Åland',
      'az': 'Azerbaïdjan',
      'ba': 'Bosnie-Herzégovine',
      'bb': 'Barbade',
      'bd': 'Bangladesh',
      'be': 'Belgique',
      'bf': 'Burkina Faso',
      'bg': 'Bulgarie',
      'bh': 'Bahreïn',
      'bi': 'Burundi',
      'bj': 'Bénin',
      'bl': 'Saint-Barthélemy',
      'bm': 'Bermudes',
      'bn': 'Brunéi Darussalam',
      'bo': 'Bolivie',
      'bq': 'Pays-Bas caribéens',
      'br': 'Brésil',
      'bs': 'Bahamas',
      'bt': 'Bhoutan',
      'bv': 'Île Bouvet',
      'bw': 'Botswana',
      'by': 'Biélorussie',
      'bz': 'Belize',
      'ca': 'Canada',
      'cc': 'Îles Cocos',
      'cd': 'Congo-Kinshasa',
      'cf': 'République centrafricaine',
      'cg': 'Congo-Brazzaville',
      'ch': 'Suisse',
      'ci': 'Côte d’Ivoire',
      'ck': 'Îles Cook',
      'cl': 'Chili',
      'cm': 'Cameroun',
      'cn': 'Chine',
      'co': 'Colombie',
      'cr': 'Costa Rica',
      'cu': 'Cuba',
      'cv': 'Cap-Vert',
      'cw': 'Curaçao',
      'cx': 'Île Christmas',
      'cy': 'Chypre',
      'cz': 'Tchéquie',
      'de': 'Allemagne',
      'dj': 'Djibouti',
      'dk': 'Danemark',
      'dm': 'Dominique',
      'do': 'République dominicaine',
      'dz': 'Algérie',
      'ec': 'Équateur',
      'ee': 'Estonie',
      'eg': 'Égypte',
      'eh': 'Sahara occidental',
      'er': 'Érythrée',
      'es': 'Espagne',
      'et': 'Éthiopie',
      'fi': 'Finlande',
      'fj': 'Fidji',
      'fk': 'Îles Malouines',
      'fm': 'États fédérés de Micronésie',
      'fo': 'Îles Féroé',
      'fr': 'France',
      'ga': 'Gabon',
      'gb': 'Royaume-Uni',
      'gd': 'Grenade',
      'ge': 'Géorgie',
      'gf': 'Guyane française',
      'gg': 'Guernesey',
      'gh': 'Ghana',
      'gi': 'Gibraltar',
      'gl': 'Groenland',
      'gm': 'Gambie',
      'gn': 'Guinée',
      'gp': 'Guadeloupe',
      'gq': 'Guinée équatoriale',
      'gr': 'Grèce',
      'gs': 'Géorgie du Sud et îles Sandwich du Sud',
      'gt': 'Guatemala',
      'gu': 'Guam',
      'gw': 'Guinée-Bissau',
      'gy': 'Guyana',
      'hk': 'R.A.S. chinoise de Hong Kong',
      'hm': 'Îles Heard et McDonald',
      'hn': 'Honduras',
      'hr': 'Croatie',
      'ht': 'Haïti',
      'hu': 'Hongrie',
      'id': 'Indonésie',
      'ie': 'Irlande',
      'il': 'Israël',
      'im': 'Île de Man',
      'in': 'Inde',
      'io': 'Territoire britannique de l’océan Indien',
      'iq': 'Irak',
      'ir': 'Iran',
      'is': 'Islande',
      'it': 'Italie',
      'je': 'Jersey',
      'jm': 'Jamaïque',
      'jo': 'Jordanie',
      'jp': 'Japon',
      'ke': 'Kenya',
      'kg': 'Kirghizistan',
      'kh': 'Cambodge',
      'ki': 'Kiribati',
      'km': 'Comores',
      'kn': 'Saint-Christophe-et-Niévès',
      'kp': 'Corée du Nord',
      'kr': 'Corée du Sud',
      'kw': 'Koweït',
      'ky': 'Îles Caïmans',
      'kz': 'Kazakhstan',
      'la': 'Laos',
      'lb': 'Liban',
      'lc': 'Sainte-Lucie',
      'li': 'Liechtenstein',
      'lk': 'Sri Lanka',
      'lr': 'Libéria',
      'ls': 'Lesotho',
      'lt': 'Lituanie',
      'lu': 'Luxembourg',
      'lv': 'Lettonie',
      'ly': 'Libye',
      'ma': 'Maroc',
      'mc': 'Monaco',
      'md': 'Moldavie',
      'me': 'Monténégro',
      'mf': 'Saint-Martin',
      'mg': 'Madagascar',
      'mh': 'Îles Marshall',
      'mk': 'Macédoine du Nord',
      'ml': 'Mali',
      'mm': 'Myanmar (Birmanie)',
      'mn': 'Mongolie',
      'mo': 'R.A.S. chinoise de Macao',
      'mp': 'Îles Mariannes du Nord',
      'mq': 'Martinique',
      'mr': 'Mauritanie',
      'ms': 'Montserrat',
      'mt': 'Malte',
      'mu': 'Maurice',
      'mv': 'Maldives',
      'mw': 'Malawi',
      'mx': 'Mexique',
      'my': 'Malaisie',
      'mz': 'Mozambique',
      'na': 'Namibie',
      'nc': 'Nouvelle-Calédonie',
      'ne': 'Niger',
      'nf': 'Île Norfolk',
      'ng': 'Nigéria',
      'ni': 'Nicaragua',
      'nl': 'Pays-Bas',
      'no': 'Norvège',
      'np': 'Népal',
      'nr': 'Nauru',
      'nu': 'Niue',
      'nz': 'Nouvelle-Zélande',
      'om': 'Oman',
      'pa': 'Panama',
      'pe': 'Pérou',
      'pf': 'Polynésie française',
      'pg': 'Papouasie-Nouvelle-Guinée',
      'ph': 'Philippines',
      'pk': 'Pakistan',
      'pl': 'Pologne',
      'pm': 'Saint-Pierre-et-Miquelon',
      'pn': 'Îles Pitcairn',
      'pr': 'Porto Rico',
      'ps': 'Territoires palestiniens',
      'pt': 'Portugal',
      'pw': 'Palaos',
      'py': 'Paraguay',
      'qa': 'Qatar',
      're': 'La Réunion',
      'ro': 'Roumanie',
      'rs': 'Serbie',
      'ru': 'Russie',
      'rw': 'Rwanda',
      'sa': 'Arabie saoudite',
      'sb': 'Îles Salomon',
      'sc': 'Seychelles',
      'sd': 'Soudan',
      'se': 'Suède',
      'sg': 'Singapour',
      'sh': 'Sainte-Hélène',
      'si': 'Slovénie',
      'sj': 'Svalbard et Jan Mayen',
      'sk': 'Slovaquie',
      'sl': 'Sierra Leone',
      'sm': 'Saint-Marin',
      'sn': 'Sénégal',
      'so': 'Somalie',
      'sr': 'Suriname',
      'ss': 'Soudan du Sud',
      'st': 'Sao Tomé-et-Principe',
      'sv': 'Salvador',
      'sx': 'Saint-Martin (partie néerlandaise)',
      'sy': 'Syrie',
      'sz': 'Eswatini',
      'tc': 'Îles Turques-et-Caïques',
      'td': 'Tchad',
      'tf': 'Terres australes françaises',
      'tg': 'Togo',
      'th': 'Thaïlande',
      'tj': 'Tadjikistan',
      'tk': 'Tokelau',
      'tl': 'Timor oriental',
      'tm': 'Turkménistan',
      'tn': 'Tunisie',
      'to': 'Tonga',
      'tr': 'Turquie',
      'tt': 'Trinité-et-Tobago',
      'tv': 'Tuvalu',
      'tw': 'Taïwan',
      'tz': 'Tanzanie',
      'ua': 'Ukraine',
      'ug': 'Ouganda',
      'um': 'Îles mineures éloignées des États-Unis',
      'us': 'États-Unis',
      'uy': 'Uruguay',
      'uz': 'Ouzbékistan',
      'va': 'État de la Cité du Vatican',
      'vc': 'Saint-Vincent-et-les-Grenadines',
      've': 'Venezuela',
      'vg': 'Îles Vierges britanniques',
      'vi': 'Îles Vierges des États-Unis',
      'vn': 'Vietnam',
      'vu': 'Vanuatu',
      'wf': 'Wallis-et-Futuna',
      'ws': 'Samoa',
      'ye': 'Yémen',
      'yt': 'Mayotte',
      'za': 'Afrique du Sud',
      'zm': 'Zambie',
      'zw': 'Zimbabwe',
    },
  };

  /// [languageCode] aceita `pt`, `pt-BR`, `en`, `es`, `fr`.
  static String displayName(String countryCode, String languageCode) {
    final iso = countryCode.trim().toLowerCase();
    if (iso.length != 2) return countryCode.trim().isEmpty ? '' : countryCode.trim().toUpperCase();
    final lang = _normalizeLang(languageCode);
    final table = byLanguage[lang] ?? byLanguage['en']!;
    return table[iso] ?? byLanguage['en']![iso] ?? iso.toUpperCase();
  }

  static String _normalizeLang(String raw) {
    final v = raw.trim().toLowerCase().replaceAll('_', '-');
    if (v.startsWith('pt')) return 'pt';
    if (v.startsWith('es')) return 'es';
    if (v.startsWith('fr')) return 'fr';
    if (v.startsWith('en')) return 'en';
    return 'en';
  }
}
