// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXJmemWYLDrdpgjADv9dP5dK9DpHpFzo',
    appId: '1:384686982032:android:3382052a7126b4b3bf2915',
    messagingSenderId: '384686982032',
    projectId: 'socialchatmvp',
    storageBucket: 'socialchatmvp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUML4TdzB6H0UWEsSIyOfw9z5O7mseY0',
    appId: '1:384686982032:web:2f9244e26d2a24a2bf2915',
    messagingSenderId: '384686982032',
    projectId: 'socialchatmvp',
    authDomain: 'socialchatmvp.firebaseapp.com',
    storageBucket: 'socialchatmvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3BS2aBpKGCXNEgSFBf4cdpgKM1vFyFI',
    appId: '1:384686982032:ios:b54447b1941d35d6bf2915',
    messagingSenderId: '384686982032',
    projectId: 'socialchatmvp',
    storageBucket: 'socialchatmvp.firebasestorage.app',
    androidClientId: '384686982032-pkl5vim1c1rb376nf95s89k617o2nobh.apps.googleusercontent.com',
    iosClientId: '384686982032-t0gf100tqvf27uircjudfbe6faavak02.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialchatMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnOBGQr2odUIt2u7uGxaVV_1xK-7ZMgAc',
    appId: '1:384686982032:web:2467ced6b4ca9149bf2915',
    messagingSenderId: '384686982032',
    projectId: 'socialchatmvp',
    authDomain: 'socialchatmvp.firebaseapp.com',
    storageBucket: 'socialchatmvp.firebasestorage.app',
  );

}